cli:
	gcc -o dist/cli src/cli.c src/parse.c src/tape.c src/interpret.c src/hashmap.c

debug:
	gcc -pg -g -o dist/cli src/cli.c src/parse.c src/tape.c src/interpret.c src/hashmap.c

clean:
	rm -rf dist
